function Nl(a,b){this.Ka=a;this.Ea=b}var Ol=new wk(0,0,1),Pl=new wk(9999,11,31);Nl.prototype.contains=function(a){return a.valueOf()>=this.Ka.valueOf()&&a.valueOf()<=this.Ea.valueOf()};var Ql={bm:"y",Wp:"y G",Xp:"MMM y",cm:"MMMM y",Kp:"MMM d",Lp:"MMMM dd",Np:"M/d",Mp:"MMMM d",Op:"MMM d, y",Tp:"EEE, MMM d",Vp:"EEE, MMM d, y",Ip:"d"},Ql={bm:"y",Wp:"y G",Xp:"MMM y",cm:"MMMM y",Kp:"d. MMM",Lp:"dd. MMMM",Np:"d.M.",Mp:"d. MMMM",Op:"d. MMM y",Tp:"EEE, d. MMM",Vp:"EEE, d. MMM y",Ip:"d"};function Rl(a,b){this.hq=a;this.H=b||Tb()}Rl.prototype.t=function(){return this.H};Rl.prototype.u=function(){return this.hq};function Sl(a,b,c,d){var f=[a.u()+"-btn"];d&&f.push(d);d=a.t().createElement("BUTTON");d.className=f.join(" ");d.appendChild(a.t().createTextNode(c));b.appendChild(d)};function Tl(a,b,c,d){T.call(this,c);this.kc=b||Z;this.Nt=this.kc.Zl;b=Z;Z=this.kc;this.ss=new Il("d");this.rs=new Il("dd");this.us=new Il("w");this.fk=new Il(Ql.bm||"y");this.ts=new Il(Ql.cm||"MMMM y");Z=b;this.q=d||new Rl(this.u(),this.t());this.oa=new wk(a);this.oa.Ff=this.kc.Ui;this.oa.$c=this.kc.Ti;this.ta=this.oa.N();this.ta.setDate(1);this.Qi="      ".split(" ");this.Qi[this.kc.am[0]]=this.u()+"-wkend-start";this.Qi[this.kc.am[1]]=this.u()+"-wkend-end";this.Ne={}}C(Tl,T);e=Tl.prototype;
e.ep=!0;e.tt=!0;e.Nl=new Nl(Ol,Pl);e.Bq=!0;e.ml=!0;e.ip=!0;e.bj=!0;e.hp=!0;e.jp=!1;e.Qm=null;e.Cs=!1;e.jh=null;e.ih=null;e.hh=null;e.mq=Me.e();e.u=function(){return"goog-date-picker"};e.Go=function(){this.ta.add(new pk(sk,-1));Ul(this);Vl(this)};e.oo=function(){this.ta.add(new pk(sk,1));Ul(this);Vl(this)};e.ht=function(){this.ta.add(new pk(rk,-1));Ul(this);Vl(this)};e.Os=function(){this.ta.add(new pk(rk,1));Ul(this);Vl(this)};e.Vo=function(){this.setDate(new wk)};e.Uo=function(){this.bj&&this.setDate(null)};
e.getDate=function(){return this.oa&&this.oa.N()};e.setDate=function(a){var b=a==this.oa||a&&this.oa&&a.getFullYear()==this.oa.getFullYear()&&a.getMonth()==this.oa.getMonth(),c=a==this.oa||b&&a.getDate()==this.oa.getDate();this.oa=a&&new wk(a);a&&(this.ta.set(this.oa),this.ta.setDate(1));Ul(this);this.dispatchEvent(new Wl("select",this,this.oa));c||this.dispatchEvent(new Wl("change",this,this.oa));b||Vl(this)};
function Xl(a,b,c,d){b=Yb(c,b);a.i().a(b,"click",function(a){a.preventDefault();d.call(this,a)})}
e.m=function(a){Tl.c.m.call(this,a);vf(a,this.u());var b=this.H.createElement("table"),c=this.H.createElement("thead"),d=this.H.createElement("tbody"),f=this.H.createElement("tfoot");Xf(d,"grid");d.tabIndex="0";this.xl=d;this.qp=f;var g=this.H.createElement("tr");g.className=this.u()+"-head";if(this.jh=g){for(var h=this.jh;h.firstChild;)h.removeChild(h.firstChild);var k=this.q,l=this.ml,n=this.kc.lf[0].toLowerCase(),t;this.jp?(n=k.t().createElement("TD"),n.colSpan=l?1:2,Sl(k,n,"«",k.u()+"-previousMonth"),
h.appendChild(n),n=k.t().createElement("TD"),n.colSpan=l?6:5,n.className=k.u()+"-monthyear",h.appendChild(n),n=k.t().createElement("TD"),Sl(k,n,"»",k.u()+"-nextMonth"),h.appendChild(n)):(l=k.t().createElement("TD"),l.colSpan=5,Sl(k,l,"«",k.u()+"-previousMonth"),Sl(k,l,"",k.u()+"-month"),Sl(k,l,"»",k.u()+"-nextMonth"),t=k.t().createElement("TD"),t.colSpan=3,Sl(k,t,"«",k.u()+"-previousYear"),Sl(k,t,"",k.u()+"-year"),Sl(k,t,"»",k.u()+"-nextYear"),n.indexOf("y")<n.indexOf("m")?(h.appendChild(t),h.appendChild(l)):
(h.appendChild(l),h.appendChild(t)));this.jp?(Xl(this,h,this.u()+"-previousMonth",this.Go),Xl(this,h,this.u()+"-nextMonth",this.oo),this.ih=Yb(this.u()+"-monthyear",h)):(Xl(this,h,this.u()+"-previousMonth",this.Go),Xl(this,h,this.u()+"-nextMonth",this.oo),Xl(this,h,this.u()+"-month",this.st),Xl(this,h,this.u()+"-previousYear",this.ht),Xl(this,h,this.u()+"-nextYear",this.Os),Xl(this,h,this.u()+"-year",this.ut),this.Fd=Yb(this.u()+"-month",h),this.Bf=Tb().j(this.u()+"-year",h))}c.appendChild(g);this.Pb=
[];for(k=0;7>k;k++){g=this.H.createElement("tr");this.Pb[k]=[];for(n=0;8>n;n++)h=this.H.createElement(0==n||0==k?"th":"td"),0!=n&&0!=k||n==k||(h.className=0==n?this.u()+"-week":this.u()+"-wday",Xf(h,0==n?"rowheader":"columnheader")),g.appendChild(h),this.Pb[k][n]=h;d.appendChild(g)}g=this.H.createElement("tr");g.className=this.u()+"-foot";if(this.hh=g)h=this.hh,hc(h),k=this.q,n=this.ml,l=k.t().createElement("TD"),l.colSpan=n?2:3,l.className=k.u()+"-today-cont",Sl(k,l,"Heute",k.u()+"-today-btn"),h.appendChild(l),
l=k.t().createElement("TD"),l.colSpan=n?4:3,h.appendChild(l),l=k.t().createElement("TD"),l.colSpan=2,l.className=k.u()+"-none-cont",Sl(k,l,"None",k.u()+"-none-btn"),h.appendChild(l),Xl(this,h,this.u()+"-today-btn",this.Vo),Xl(this,h,this.u()+"-none-btn",this.Uo),this.$m=Yb(this.u()+"-today-btn",h),this.Zm=Yb(this.u()+"-none-btn",h),De(this.$m,this.hp),De(this.Zm,this.bj),De(this.qp,this.hp||this.bj);f.appendChild(g);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(d);b.appendChild(f);
a.appendChild(b);if(this.b()){if(this.ip)for(b=0;7>b;b++)oc(this.Pb[0][b+1],this.Nt[((b+this.ta.$c+7)%7+1)%7]);De(this.Pb[0][0].parentNode,this.ip)}Ul(this);a.tabIndex=0};e.f=function(){Tl.c.f.call(this);this.m(this.b())};e.d=function(){Tl.c.d.call(this);var a=this.i();a.a(this.xl,"click",this.or);a.a(Yl(this,this.b()),"key",this.pr)};e.Sa=function(){Tl.c.Sa.call(this);this.ve();for(var a in this.Ne)this.Ne[a].l();this.Ne={}};
e.h=function(){Tl.c.h.call(this);this.Zm=this.$m=this.Bf=this.ih=this.Fd=this.hh=this.jh=this.qp=this.xl=this.Pb=null};e.or=function(a){if("TD"==a.target.tagName){var b,c=-2,d=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,d++);a=this.De[d][c];this.Nl.contains(a)&&this.setDate(a.N())}};
e.pr=function(a){var b,c;switch(a.keyCode){case 33:a.preventDefault();b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault(),this.Vo();case 46:a.preventDefault(),this.Uo();default:return}this.oa?(a=this.oa.N(),a.add(new pk(0,b,c))):(a=this.ta.N(),a.setDate(1));this.Nl.contains(a)&&this.setDate(a)};
e.st=function(a){a.stopPropagation();a=[];for(var b=0;12>b;b++)a.push(this.kc.mf[b]);Zl(this,this.Fd,a,this.Ar,this.kc.mf[this.ta.getMonth()])};e.ut=function(a){a.stopPropagation();a=[];for(var b=this.ta.getFullYear(),c=this.ta.N(),d=-5;5>=d;d++)c.setFullYear(b+d),a.push(this.fk.format(c));Zl(this,this.Bf,a,this.os,this.fk.format(this.ta))};e.Ar=function(a){a=Number(a.getAttribute("itemIndex"));this.ta.setMonth(a);Ul(this);this.Fd.focus&&this.Fd.focus()};
e.os=function(a){3==a.firstChild.nodeType&&(a=Number(a.getAttribute("itemIndex")),this.ta.setFullYear(this.ta.getFullYear()+a-5),Ul(this));this.Bf.focus()};
function Zl(a,b,c,d,f){a.ve();var g=a.H.createElement("div");g.className=a.u()+"-menu";a.Ue=null;for(var h=a.H.createElement("ul"),k=0;k<c.length;k++){var l=a.H.f("li",null,c[k]);l.setAttribute("itemIndex",k);c[k]==f&&(a.Ue=l);h.appendChild(l)}g.appendChild(h);g.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";g.style.top=b.offsetTop+"px";g.style.width=b.clientWidth+"px";a.Fd.parentNode.appendChild(g);a.p=g;a.Ue||(a.Ue=h.firstChild);a.Ue.className=a.u()+"-menu-selected";a.Ak=d;b=a.i();b.a(a.p,
"click",a.Bn);b.a(Yl(a,a.p),"key",a.Cn);b.a(a.H.O,"click",a.ve);g.tabIndex=0;g.focus()}e.Bn=function(a){a.stopPropagation();this.ve();this.Ak&&this.Ak(a.target)};
e.Cn=function(a){a.stopPropagation();var b,c=this.Ue;switch(a.keyCode){case 35:a.preventDefault();b=c.parentNode.lastChild;break;case 36:a.preventDefault();b=c.parentNode.firstChild;break;case 38:a.preventDefault();b=c.previousSibling;break;case 40:a.preventDefault();b=c.nextSibling;break;case 13:case 9:case 0:a.preventDefault(),this.ve(),this.Ak(c)}b&&b!=c&&(c.className="",b.className=this.u()+"-menu-selected",this.Ue=b)};
e.ve=function(){if(this.p){var a=this.i();a.L(this.p,"click",this.Bn);a.L(Yl(this,this.p),"key",this.Cn);a.L(this.H.O,"click",this.ve);ic(this.p);delete this.p}};
function Ul(a){if(a.b()){var b=a.ta.N();b.setDate(1);a.ih&&oc(a.ih,a.ts.format(b));a.Fd&&oc(a.Fd,a.kc.mf[b.getMonth()]);a.Bf&&oc(a.Bf,a.fk.format(b));var c=((b.getDay()+6)%7-b.$c+7)%7,d=nk(b.getFullYear(),b.getMonth());b.add(new pk(sk,-1));b.setDate(nk(b.getFullYear(),b.getMonth())-(c-1));a.ep&&!a.Bq&&33>d+c&&b.add(new pk(qk,-7));c=new pk(qk,1);a.De=[];for(d=0;6>d;d++){a.De[d]=[];for(var f=0;7>f;f++)a.De[d][f]=b.N(),b.add(c)}if(a.b())for(var b=a.ta.getMonth(),f=new wk,c=f.getFullYear(),d=f.getMonth(),
f=f.getDate(),g=0;6>g;g++){a.ml?(oc(a.Pb[g+1][0],a.us.format(a.De[g][0])),a.Pb[g+1][0].className=a.u()+"-week"):(oc(a.Pb[g+1][0],""),a.Pb[g+1][0].className="");for(var h=0;7>h;h++){var k=a.De[g][h],l=a.Pb[g+1][h+1];l.id||(l.id=Ne(a.mq));Xf(l,"gridcell");var n=[a.u()+"-date"];a.Nl.contains(k)||n.push(a.u()+"-unavailable-date");if(a.tt||k.getMonth()==b){k.getMonth()!=b&&n.push(a.u()+"-other-month");var t=(h+a.ta.$c+7)%7;a.Qi[t]&&n.push(a.Qi[t]);k.getDate()==f&&k.getMonth()==d&&k.getFullYear()==c&&n.push(a.u()+
"-today");a.oa&&k.getDate()==a.oa.getDate()&&k.getMonth()==a.oa.getMonth()&&k.getFullYear()==a.oa.getFullYear()&&(n.push(a.u()+"-selected"),W(a.xl,"activedescendant",l.id));a.Qm&&(t=a.Qm(k))&&n.push(t);k=a.Cs?a.rs.format(k):a.ss.format(k);oc(l,k)}else oc(l,"");l.className=n.join(" ")}4<=g&&De(a.Pb[g+1][0].parentNode,a.De[g][0].getMonth()==b||a.ep)}}}function Vl(a){var b=new Wl("changeActiveMonth",a,a.ta.N());a.dispatchEvent(b)}
function Yl(a,b){var c=ja(b);c in a.Ne||(a.Ne[c]=new Qf(b));return a.Ne[c]}function Wl(a,b,c){P.call(this,a,b);this.s=c}C(Wl,P);function $l(a,b){R.call(this);this.r=new S(this);if(this.fa)throw Error("Can not change this state of the popup while showing.");this.g=a||null;b&&this.Ci(b)}C($l,R);e=$l.prototype;e.g=null;e.eq=!0;e.nm=null;e.fa=!1;e.rt=!1;e.uk=-1;e.ps=!1;e.yq=!0;e.ff="toggle_display";e.Ci=function(a){this.ff=a};e.b=function(){return this.g};e.i=function(){return this.r};e.S=function(){return this.fa};
e.setVisible=function(a){this.tg&&this.tg.stop();this.Vf&&this.Vf.stop();if(a){if(!this.fa&&this.dispatchEvent("beforeshow")){if(!this.g)throw Error("Caller must call setElement before trying to show the popup");this.Yb();a=N(this.g);this.ps&&this.r.a(a,"keydown",this.Ss,!0);if(this.eq)if(this.r.a(a,"mousedown",this.ro,!0),G){var b;try{b=a.activeElement}catch(c){}for(;b&&"IFRAME"==b.nodeName;){try{var d=nc(b)}catch(f){break}a=d;b=a.activeElement}this.r.a(a,"mousedown",this.ro,!0);this.r.a(a,"deactivate",
this.qo)}else this.r.a(a,"blur",this.qo);"toggle_display"==this.ff?(this.g.style.visibility="visible",De(this.g,!0)):"move_offscreen"==this.ff&&this.Yb();this.fa=!0;this.uk=B();this.tg?(ed(this.tg,"end",this.ci,!1,this),this.tg.play()):this.ci()}}else am(this)};e.Yb=r;function am(a,b){if(!a.fa||!a.dispatchEvent({type:"beforehide",target:b}))return!1;a.r&&a.r.ub();a.fa=!1;B();a.Vf?(ed(a.Vf,"end",oa(a.Em,b),!1,a),a.Vf.play()):a.Em(b);return!0}
e.Em=function(a){"toggle_display"==this.ff?this.rt?qd(this.Jn,0,this):this.Jn():"move_offscreen"==this.ff&&(this.g.style.top="-10000px");this.dispatchEvent({type:"hide",target:a})};e.Jn=function(){this.g.style.visibility="hidden";De(this.g,!1)};e.ci=function(){this.dispatchEvent("show")};e.ro=function(a){a=a.target;mc(this.g,a)||this.nm&&!mc(this.nm,a)||150>B()-this.uk||am(this,a)};e.Ss=function(a){27==a.keyCode&&am(this,a.target)&&(a.preventDefault(),a.stopPropagation())};
e.qo=function(a){if(this.yq){var b=N(this.g);if("undefined"!=typeof document.activeElement){if(a=b.activeElement,!a||mc(this.g,a)||"BODY"==a.tagName)return}else if(a.target!=b)return;150>B()-this.uk||am(this)}};e.h=function(){$l.c.h.call(this);this.r.l();Ec(this.tg);Ec(this.Vf);delete this.g;delete this.r};function bm(a,b){this.et=4;this.ji=b||void 0;$l.call(this,a)}C(bm,$l);bm.prototype.getPosition=function(){return this.ji||null};bm.prototype.setPosition=function(a){this.ji=a||void 0;this.S()&&this.Yb()};bm.prototype.Yb=function(){if(this.ji){var a=!this.S()&&"move_offscreen"!=this.ff,b=this.b();a&&(b.style.visibility="hidden",De(b,!0));this.ji.Yb(b,this.et,this.bw);a&&De(b,!1)}};function cm(a,b){T.call(this,b);this.La=a||new Tl}C(cm,T);e=cm.prototype;e.La=null;e.hc=null;e.Uh=null;e.wd=!0;e.f=function(){cm.c.f.call(this);this.b().className="goog-popupdatepicker";this.hc=new bm(this.b());this.hc.$b(this)};e.S=function(){return this.hc?this.hc.S():!1};e.d=function(){cm.c.d.call(this);if(!this.La.F){var a=this.b();a.style.visibility="hidden";De(a,!1);this.La.R(a)}this.i().a(this.La,"change",this.cg)};
e.h=function(){cm.c.h.call(this);this.hc&&(this.hc.l(),this.hc=null);this.La.l();this.Uh=this.La=null};e.ib=function(){return!1};e.Hj=function(){return this.La};e.getDate=function(){return this.La.getDate()};e.setDate=function(a){this.La.setDate(a)};e.of=function(a){this.i().a(a,"mousedown",this.fp)};e.detach=function(a){this.i().L(a,"mousedown",this.fp)};e.gl=function(a){this.wd=a};
e.fp=function(a){this.Uh=a=a.currentTarget;this.hc.setPosition(new Fk(a,5,197));this.i().L(this.La,"change",this.cg);this.La.setDate(null);this.dispatchEvent("show");this.i().a(this.La,"change",this.cg);this.hc.setVisible(!0);this.wd&&this.b().focus()};e.ck=function(){this.hc.setVisible(!1);this.wd&&this.Uh&&this.Uh.focus()};e.cg=function(a){this.ck();this.dispatchEvent(a)};function dm(a,b,c,d){T.call(this,d);this.sj=a;this.Nm=b;this.ma=new cm(c,d);this.B(this.ma);this.ma.gl(!1)}C(dm,T);e=dm.prototype;e.sj=null;e.Nm=null;e.ma=null;e.Fo=null;e.Hj=function(){return this.ma.Hj()};e.getDate=function(){var a=em(this),b=this.ma.getDate();a&&b?a.equals(b)||this.ma.setDate(a):this.ma.setDate(null);return a};e.setDate=function(a){this.ma.setDate(a)};function fm(a,b){var c=a.b();c.sk?c.sk.A(b):c.value=b}
function em(a){var b;b=a.b();b=b.sk?b.sk.o():b.value;if(b=ya(b)){var c=new Ak;if(0<gm(a.Nm,b,c,0,!0))return c}return null}e.f=function(){this.g=this.t().f("input",{type:"text"});this.ma.f()};e.d=function(){dm.c.d.call(this);var a=this.b();(this.Fo||vc(this.t()).body).appendChild(this.ma.b());this.ma.d();this.ma.of(a);this.ma.setDate(em(this));a=this.i();a.a(this.ma,"change",this.cg);a.a(this.ma,"show",this.Ys)};e.Sa=function(){dm.c.Sa.call(this);this.ma.detach(this.b());this.ma.Sa();ic(this.ma.b())};
e.m=function(a){dm.c.m.call(this,a);this.ma.f()};e.h=function(){dm.c.h.call(this);this.ma.l();this.Fo=this.ma=null};e.ck=function(){this.ma.ck()};e.Ys=function(){var a=em(this);this.setDate(a);a&&(a=this.Hj().getDate(),fm(this,a?this.sj.format(a):""))};e.cg=function(a){a=a.s;fm(this,a?this.sj.format(a):"")};function hm(a){pg.call(this,a);a=new Il("d.M.y");var b=new im("d.M.y");this.La=new dm(a,b);Dc(this,this.La)}C(hm,pg);hm.prototype.d=function(){hm.c.d.call(this);this.La.R(this.b());this.i().a(this.La,"change",this.Vq)};hm.prototype.Vq=function(){this.sh()};yf("datepicker",function(){return new hm("")});function jm(a){Ak.call(this,a||0);this.Hh=!1}C(jm,Ak);jm.prototype.Ge=function(){return this.Hh};jm.prototype.ee=function(a){this.Hh=a};jm.prototype.toString=function(){return $.rq(this)};jm.prototype.N=function(){var a=new jm(this.s);a.Hh=this.Hh;return a};function km(a){var b=new jm;return ok(b,a)?b:null};function im(a){this.ea=[];"number"==typeof a?this.Ng(a):this.nf(a)}
im.prototype.nf=function(a){for(var b=!1,c="",d=0;d<a.length;d++){var f=a.charAt(d);if(" "==f)for(0<c.length&&(this.ea.push({text:c,count:0,me:!1}),c=""),this.ea.push({text:" ",count:0,me:!1});d<a.length-1&&" "==a.charAt(d+1);)d++;else if(b)"'"==f?d+1<a.length&&"'"==a.charAt(d+1)?(c+="'",d++):b=!1:c+=f;else if(0<=lm.indexOf(f)){0<c.length&&(this.ea.push({text:c,count:0,me:!1}),c="");var g;g=a.charAt(d);for(var h=d+1;h<a.length&&a.charAt(h)==g;)h++;g=h-d;this.ea.push({text:f,count:g,me:!1});d+=g-1}else"'"==
f?d+1<a.length&&"'"==a.charAt(d+1)?(c+="'",d++):b=!0:c+=f}0<c.length&&this.ea.push({text:c,count:0,me:!1});a=!1;for(b=0;b<this.ea.length;b++)mm(this.ea[b])?!a&&b+1<this.ea.length&&mm(this.ea[b+1])&&(a=!0,this.ea[b].me=!0):a=!1};im.prototype.Ng=function(a){var b;11<a&&(a=10);4>a?b=Z.lf[a]:8>a?b=Z.Jg[a-4]:(b=Z.Rl[a-8],b=b.replace("{1}",Z.lf[a-8]),b=b.replace("{0}",Z.Jg[a-8]));this.nf(b)};im.prototype.parse=function(a,b,c){return gm(this,a,b,c||0,!1)};
function gm(a,b,c,d,f){for(var g=new nm,h=[d],k=-1,l=0,n=0,t=0;t<a.ea.length;t++)if(0<a.ea[t].count)if(0>k&&a.ea[t].me&&(k=t,l=d,n=0),0<=k){var w=a.ea[t].count;if(t==k&&(w-=n,n++,0==w))return 0;om(b,h,a.ea[t],w,g)||(t=k-1,h[0]=l)}else{if(k=-1,!om(b,h,a.ea[t],0,g))return 0}else{k=-1;if(" "==a.ea[t].text.charAt(0)){if(w=h[0],pm(b,h),h[0]>w)continue}else if(b.indexOf(a.ea[t].text,h[0])==h[0]){h[0]+=a.ea[t].text.length;continue}return 0}a:if(void 0!=g.dn&&void 0!=g.Tc&&0==g.dn&&0<g.Tc&&(g.Tc=-(g.Tc-1)),
void 0!=g.Tc&&c.setFullYear(g.Tc),a=c.getDate(),c.setDate(1),void 0!=g.Ve&&c.setMonth(g.Ve),void 0!=g.day?c.setDate(g.day):(b=nk(c.getFullYear(),c.getMonth()),c.setDate(a>b?b:a)),z(c.setHours)&&(void 0==g.ia&&(g.ia=c.getHours()),void 0!=g.km&&0<g.km&&12>g.ia&&(g.ia+=12),c.setHours(g.ia)),z(c.setMinutes)&&void 0!=g.Ha&&c.setMinutes(g.Ha),z(c.setSeconds)&&void 0!=g.Ja&&c.setSeconds(g.Ja),z(c.setMilliseconds)&&void 0!=g.Bk&&c.setMilliseconds(g.Bk),f&&(void 0!=g.Tc&&g.Tc!=c.getFullYear()||void 0!=g.Ve&&
g.Ve!=c.getMonth()||void 0!=g.day&&g.day!=c.getDate()||24<=g.ia||60<=g.Ha||60<=g.Ja||1E3<=g.Bk))c=!1;else{void 0!=g.Gl&&c.setTime(c.getTime()+6E4*(g.Gl-c.getTimezoneOffset()));g.cq&&(f=new Date,f.setFullYear(f.getFullYear()-80),c.getTime()<f.getTime()&&c.setFullYear(f.getFullYear()+100));if(void 0!=g.tj)if(void 0==g.day)g=(7+g.tj-c.getDay())%7,3<g&&(g-=7),f=c.getMonth(),c.setDate(c.getDate()+g),c.getMonth()!=f&&c.setDate(c.getDate()+(0<g?-7:7));else if(g.tj!=c.getDay()){c=!1;break a}c=!0}return c?
h[0]-d:0}var lm="GyMdkHmsSEDahKzZvQL";function mm(a){if(0>=a.count)return!1;var b="MydhHmsSDkK".indexOf(a.text.charAt(0));return 0<b||0==b&&3>a.count}function pm(a,b){var c=a.substring(b[0]).match(/^\s+/);c&&(b[0]+=c[0].length)}
function om(a,b,c,d,f){pm(a,b);var g=b[0],h=c.text.charAt(0),k=-1;if(mm(c))if(0<d){if(g+d>a.length)return!1;k=qm(a.substring(0,g+d),b)}else k=qm(a,b);switch(h){case "G":return f.dn=rm(a,b,Z.Sl),!0;case "M":case "L":a:{c=k;if(0>c){c=rm(a,b,Z.Tl.concat(Z.mf).concat(Z.Vl).concat(Z.Yl));if(0>c){f=!1;break a}f.Ve=c%12}else f.Ve=c-1;f=!0}return f;case "E":return c=rm(a,b,Z.$l),0>c&&(c=rm(a,b,Z.Xl)),0>c?f=!1:(f.tj=c,f=!0),f;case "a":return f.km=rm(a,b,Z.Ql),!0;case "y":a:{var l;if(0>k){l=a.charAt(b[0]);
if("+"!=l&&"-"!=l){f=!1;break a}b[0]++;k=qm(a,b);if(0>k){f=!1;break a}"-"==l&&(k=-k)}l||2!=b[0]-g||2!=c.count?f.Tc=k:(a=k,b=(new Date).getFullYear()-80,c=b%100,f.cq=a==c,a+=100*Math.floor(b/100)+(a<c?100:0),f.Tc=a);f=!0}return f;case "Q":return 0>k?(c=rm(a,b,Z.Ul),0>c&&(c=rm(a,b,Z.Wl)),0>c?f=!1:(f.Ve=3*c,f.day=1,f=!0)):f=!1,f;case "d":return f.day=k,!0;case "S":return a=b[0]-g,f.Bk=3>a?k*Math.pow(10,3-a):Math.round(k/Math.pow(10,a-3)),!0;case "h":12==k&&(k=0);case "K":case "H":case "k":return f.ia=
k,!0;case "m":return f.Ha=k,!0;case "s":return f.Ja=k,!0;case "z":case "Z":case "v":a.indexOf("GMT",b[0])==b[0]&&(b[0]+=3);a:if(b[0]>=a.length)f.Gl=0,f=!0;else{c=1;switch(a.charAt(b[0])){case "-":c=-1;case "+":b[0]++}g=b[0];k=qm(a,b);if(0==k&&b[0]==g)f=!1;else{if(b[0]<a.length&&":"==a.charAt(b[0])){l=60*k;b[0]++;g=b[0];k=qm(a,b);if(0==k&&b[0]==g){f=!1;break a}l+=k}else l=k,l=24>l&&2>=b[0]-g?60*l:l%100+l/100*60;f.Gl=-(l*c);f=!0}}return f;default:return!1}}
function qm(a,b){if(Z.Wi){for(var c=[],d=b[0];d<a.length;d++){var f=a.charCodeAt(d)-Z.Wi;c.push(0<=f&&9>=f?String.fromCharCode(f+48):a.charAt(d))}a=c.join("")}else a=a.substring(b[0]);c=a.match(/^\d+/);if(!c)return-1;b[0]+=c[0].length;return parseInt(c[0],10)}function rm(a,b,c){var d=0,f=-1;a=a.substring(b[0]).toLowerCase();for(var g=0;g<c.length;g++){var h=c[g].length;h>d&&0==a.indexOf(c[g].toLowerCase())&&(f=g,d=h)}0<=f&&(b[0]+=d);return f}function nm(){};var $={};$.qq=[new im("dd'.'MM'.'yyyy"),new im("yyy-MM-dd"),new im("yyy/MM/dd")];$.Ct=new im("HH:mm");$.ie=function(a){if(!a)return null;var b=new jm,c=$.ct(a,b);0<c&&$.Do(a.substring(c),b);return 0<c?b:null};$.ct=function(a,b){for(var c=$.qq,d=0,f=0;f<c.length&&!(d=gm(c[f],a,b,0,!0),0<d);f++);return d};$.Do=function(a,b){return 0<gm($.Ct,a,b,0,!0)?(b.ee(!0),!0):!1};$.wt=function(a,b){var c=$.ie(a);if(!b)return c;if(!c){var d=b.N();0<$.Do(a,d)&&(c=d)}return c};$.As=function(a){return/^\d+$/.test(a)};
$.dt=function(a){var b={};$.As(a)?b.index=parseInt(a,10):(b.s=$.ie(a),b.s||(b.Mt="Cannot parse index or date: "+a));return b};$.rq=function(a){var b=$.Om(a);a.Ge()&&(b+=" "+$.Fi(a));return b};$.pq=new Il("d.M.y");$.Bt=new Il("H:m");$.Fi=function(a){return $.Bt.format(a)};$.Om=function(a){return $.pq.format(a)};function sm(a,b){T.call(this);this.P=a;b||new jm;this.k=new If}C(sm,T);sm.prototype.f=function(){var a=this.t(),a=a.f("div","exclude-date",[a.f("div",{"class":"remove-btn","data-tooltip":"remove"})]);this.m(a)};sm.prototype.d=function(){sm.c.d.call(this);this.La=Df(this.k.X("Exclude Date","datepicker",{w:"excl-date"}));this.B(this.k,!0);this.i().a(this.j("remove-btn"),"click",this.Or)};sm.prototype.Or=function(){};function tm(a){Bk.call(this);this.P=a||new um;this.P.$b(this);this.no=!a;this.k=new If}C(tm,Bk);
tm.prototype.d=function(){tm.c.d.call(this);K(this.b(),"calendar-tile");var a=this.t().f("button","btn add-exclude-btn hidden","exclude date");this.b().appendChild(a);this.Ka=Df(this.k.X("","datepicker",{w:"start"}));this.xg=Df(this.k.X("","textbox",{w:"start-time"}));this.cn=Df(this.k.X("to","textbox",{w:"end-time"}));this.Ea=Df(this.k.X("","datepicker",{w:"end"}));var b=this.k.X("All day","checkbox",{w:"all-day"});this.hm=b.ga;K(b.b(),"all-day-row");for(var b=[],c=1;30>c;c++)b.push({text:c+" ",
Gc:c});this.Io=Df(this.k.X("widerholender Termin","checkbox",{w:"recurrent-cb"}));this.Vk=Df(this.k.X("","select",{w:"recurrent",options:b}));this.Vk.rg(0);this.Uk=Df(this.k.X("","select",{w:"recurrent-type",options:[{text:"daily",Gc:"d"},{text:"weekly",Gc:"w"},{text:"monthly",Gc:"m"},{text:"yearly",Gc:"y"}]}));this.Uk.rg(0);this.nd=Df(this.k.X("ends","datepicker",{w:"recend"}));b=this.P;this.no&&(c=new jm(new Date),c.setSeconds(0),c.setMilliseconds(0),30<c.getMinutes()?(c.setHours(c.getHours()+1),
c.setMinutes(0)):c.setMinutes(30),c.ee(!0),vm(b,c,void 0,!0),c=c.N(),c.ee(!0),c.add(new pk(tk,1)),wm(b,c,void 0,!0),xm(b),this.no=!1);ym(this.Ka,b.Ka);var c=this.xg,d=$.Fi(b.Ka);c.A(d);ym(this.Ea,b.Ea);c=this.cn;d=$.Fi(b.Ea);c.A(d);ym(this.nd,b.nd);c=b.Ge();this.hm.A(!c);b.ae&&(d=b.ae,this.Uk.A(d.Ni),this.Vk.A(d.ai),this.Io.A(!0));this.k.F||this.B(this.k,!0);zm(this,!!b.ae);Am(this,c);this.i().a(this.k,"change",this.mr).a(a,"click",this.Lq)};
function ym(a,b){if(b){var c=$.Om(b);a.A(c)}else a.A("")}
tm.prototype.mr=function(a){a=a.target.qa;var b=this.P,c="1"===this.hm.o(),d="";switch(a){case "start":case "start-time":c||(d=" "+this.xg.o());a=$.ie(this.Ka.o()+d);vm(this.P,a);break;case "end":case "end-time":c||(d=" "+this.cn.o());a=$.ie(this.Ea.o()+d);wm(this.P,a);break;case "all-day":Am(this,!c);b.ee(!c);break;case "recurrent-cb":if(a="1"===this.Io.o(),zm(this,a),!a){Bm(this.P,null);break}case "recurrent":case "recurrent-type":a=this.Uk.o();b=this.Vk.o();Bm(this.P,new Cm(b,a));break;case "recend":a=
$.ie(this.nd.o()),Dm(this.P,a)}};function zm(a,b){L(Jf(a.k,"recurrent").b(),"hidden",!b);L(Jf(a.k,"recurrent-type").b(),"hidden",!b);L(Kf(a.k,"recend").b(),"hidden",!b)}function Am(a,b){L(Kf(a.k,"start-time").b(),"hidden",!b);L(Kf(a.k,"end-time").b(),"hidden",!b)}tm.prototype.Lq=function(){var a=new sm(this.P);this.B(a,!0)};function Cm(a,b){this.ai=a;this.Ni=b}Cm.prototype.toString=function(){return this.ai+this.Ni};Cm.prototype.equals=function(a){return a&&a.ai===this.ai&&a.Ni===this.Ni};function um(){R.call(this);this.ae=this.Ea=this.Ka=null;this.nh=[];this.nd=null;this.Oa={}}C(um,R);
function Em(a){var b=new um;b.Ka=a.start?km(a.start):null;b.Ea=a.end?km(a.end):null;var c;if(a.recurrent){c=a.recurrent;var d=0,f="d",g;for(g in c)if(0<c[g]){d=c[g];switch(g){case "days":0===d%7?(f="w",d/=7):f="d";break;case "months":f="m";break;case "years":f="y"}break}c=new Cm(d,f)}else c=null;b.ae=c;b.nd=a.recend?km(a.recend):null;if(v(a.exclude))for(c=0;c<a.exclude.length;c++)b.nh.push(km(a.exclude[c]));return b}
function vm(a,b,c,d){a.Ka=b;u(c)?a.Oa.start=c:a.dispatchEvent({type:"changed_tag",tagName:"start",value:b.toString(),Ya:a.Oa.start,li:!!d})}function wm(a,b,c,d){a.Ea=b;if(u(c))a.Oa.end=c;else{c="";if(c=a.Ea.Ge()){c=a.Ka;var f=a.Ea||new Date(B()),g;if(g=c.getDate()==f.getDate())if(f=f||new Date(B()),g=c.getMonth()==f.getMonth())f=f||new Date(B()),g=c.getFullYear()==f.getFullYear();c=g}c=c?$.Fi(b):b.toString();a.dispatchEvent({type:"changed_tag",tagName:"end",value:c,Ya:a.Oa.end,li:!!d})}}e=um.prototype;
e.ee=function(a){this.Ka.ee(a);this.Ea.ee(a);vm(this,this.Ka,void 0,!0);wm(this,this.Ea,void 0,!0);xm(this)};e.Ge=function(){return this.Ka.Ge()||this.Ea.Ge()};function Bm(a,b,c){a.ae=b;u(c)?a.Oa.recurrent=c:a.dispatchEvent({type:"changed_tag",tagName:"recurrent",value:b?b.toString():"",Ya:a.Oa.recurrent,pi:!b})}function Dm(a,b,c){a.nd=b;u(c)?a.Oa.recend=c:a.dispatchEvent({type:"changed_tag",tagName:"recend",value:b?b.toString():"",Ya:a.Oa.recend,pi:!b})}e.ln=function(a){return this.Oa[a]||null};
e.Il=function(a){return this.Oa=a.Oa};function xm(a){a.dispatchEvent("changed_tag_update")}e.equals=function(a){return Fm(this.Ka,a.Ka)&&Fm(this.Ea,a.Ea)&&Fm(this.ae,a.ae)&&Fm(this.nd,a.nd)&&Gm(this.nh,a.nh)};function Fm(a,b){return a&&!b||!a&&b?!1:!a&&!b||a.equals(b)}function Gm(a,b){return fb(a,b,function(a,b){return a.equals(b)})};var Hm=$;function Im(){this.id="calParser"}Im.prototype.parse=function(a){var b=[],c=a.fl;if(v(c.cal))for(a=0;a<c.cal.length;a++)b.push(Em(c.cal[a]));else b=Jm(this,a.rf);return b};
function Jm(a,b){var c=[],d=new um,f=!1;E(b,function(a){if(a.key){var h=a.key.toLowerCase();"start"===h?(d.Ka&&d.Ea&&c.push(d),d=new um,vm(d,Hm.ie(a.value),a.Ya)):"end"===h?wm(d,Hm.wt(a.value,d.Ka),a.Ya):"recend"===h?Dm(d,Hm.ie(a.value),a.Ya):"recurrent"!==h||f||(f=!0,h=/^(\d+)([dwmy])$/.exec(a.value.toLowerCase()),Bm(d,null===h?null:new Cm(parseInt(h[1],10),h[2]),a.Ya),a=Km(this,b),d.nh=a)}},a);d.Ka&&d.Ea&&c.push(d);return c}
function Km(a,b){var c=Qa(b,function(a){return"exc"===a.key});return Sa(c,function(a){var b=a.value;(a=/^([^\s,]+)\s*(?:,\s*(\w+))?$/.exec(b))?(b=Hm.dt(a[1]),a[2]&&(b.id=a[2]),a=b):a={Mt:"Cannot parse "+b};return a},a)};function Lm(a,b){Mm.call(this,a,b);this.Jh="icon-event";this.Jb="Kalender";this.tf=[]}C(Lm,Mm);Lm.prototype.ja=function(){this.i().a(this.ca,hk,this.Tb);Nm(this)};Lm.prototype.Kj=function(){var a=new tm;this.tf.push(a.P);return a};Lm.prototype.Tb=function(){Nm(this)};function Nm(a){var b=a.ca.yc().Lf(Im);if(fb(a.tf,b,function(a,b){return a.equals(b)}))for(c=0;c<a.tf.length;c++)a.tf[c].Il(b[c]);else{a.tf=b;a.Wk();for(var c=0;c<b.length;c++){var d=new tm(b[c]);a.ne(d);a.i().a(d,"close",a.bs)}}}
Lm.prototype.bs=function(a){a=a.target.P;for(var b in a.Oa)a.dispatchEvent({type:"changed_tag",tagName:b,Ya:a.Oa[b],pi:!0,li:!0});xm(a)};function Om(){}Om.prototype.ja=function(){Pm.e().od.X("Today","checkbox",{w:"today"});var a=Pm.e().od;Q(a,Qm,this.Qf,!1,this)};Om.prototype.Qf=function(a){"1"==a.Gj.today&&(a.ng.Kl.daterange="today")};function Rm(){O.call(this)}C(Rm,aj);Rm.prototype.ka=function(){jk(Lm);(new Om).ja()};Zi("calendar",Rm);
//@ sourceURL=/asset/common/js-min/LANG/calendar.js